name: Laravel CI

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        php-version: [8.2]  # Use PHP 8.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Generate Laravel App Key
        run: php artisan key:generate