name: Laravel CI

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        php-version: [8.2]  # Use PHP 8.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Node.js Dependencies
        run: npm install

      - name: Build Frontend Assets
        run: npm run build

      - name: Set Permissions for Storage
        run: |
          sudo chown -R www-data:www-data /var/www/probasi/_work/probasitripurabashi/probasitripurabashi/storage
          sudo chmod -R 775 /var/www/probasi/_work/probasitripurabashi/probasitripurabashi/storage
